# 项目基础配置
app:
  name: "Academic Paper Analysis Agent"
  version: "1.0.0"
  environment: "development"
  debug: true
  api_prefix: "/api"  # 移除v1

# 服务器配置
server:
  host: "0.0.0.0"
  port: 8000
  workers: 4
  reload: true

# 数据库配置（敏感信息从.env读取）
database:
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800

# CORS配置
cors:
  allow_origins: ["*"]
  allow_methods: ["*"]
  allow_headers: ["*"]
  allow_credentials: true

# 知识图谱分析配置
kg_analysis:
  # 路径分析配置
  path_analysis:
    max_depth: 5  # 默认最大搜索深度
    max_paths: 10  # 默认最大返回路径数量
    timeout: 30  # 搜索超时时间（秒）
    cache_ttl: 3600  # 缓存时间（秒）

  # 相关性分析配置
  relation_analysis:
    max_depth: 3  # 默认最大搜索深度
    max_relations: 20  # 默认最大返回关系数量
    min_weight: 0.0  # 默认最小关系权重
    decay_factor: 0.5  # 关系权重衰减因子
    timeout: 30  # 分析超时时间（秒）
    cache_ttl: 3600  # 缓存时间（秒）

  # 循环检测配置
  cycle_detection:
    max_depth: 10  # 默认最大搜索深度
    timeout: 30  # 检测超时时间（秒）
    cache_ttl: 3600  # 缓存时间（秒）

  # 统计分析配置
  statistics:
    cache_ttl: 3600  # 缓存时间（秒）
    update_interval: 300  # 统计信息更新间隔（秒）
    max_time_points: 100  # 时间序列最大点数

# 缓存配置
cache:
  enabled: true
  type: "redis"  # 可选：redis, memory
  prefix: "kg:"
  default_ttl: 3600

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/kg.log"
  max_size: 10485760  # 10MB
  backup_count: 5
  
# 性能优化配置
performance:
  batch_size: 1000  # 批量操作大小
  max_workers: 4  # 最大工作线程数
  query_timeout: 30  # 查询超时时间（秒） 
