# 开发环境特定配置
project:
  debug: true
  environment: "development"

server:
  reload: true
  workers: 1

database:
  pool_size: 5
  max_overflow: 5

cors:
  allow_origins: ["*"]

cache:
  enabled: false
  type: "memory"

logging:
  level: "DEBUG"
  
performance:
  max_workers: 2 