"""recreate_all_tables

Revision ID: 4cb3fad9633c
Revises: 
Create Date: 2025-01-25 14:25:18.528133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb3fad9633c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    
    op.create_table('import_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('entities_count', sa.Integer(), nullable=True),
    sa.Column('relationships_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_records_id'), 'import_records', ['id'], unique=False)
    
    op.create_table('statistics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cache_value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_cache_cache_key'), 'statistics_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_statistics_cache_expires_at'), 'statistics_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_statistics_cache_id'), 'statistics_cache', ['id'], unique=False)
    
    op.create_table('statistics_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_task_created_at'), 'statistics_task', ['created_at'], unique=False)
    op.create_index(op.f('ix_statistics_task_id'), 'statistics_task', ['id'], unique=False)
    op.create_index(op.f('ix_statistics_task_status'), 'statistics_task', ['status'], unique=False)
    op.create_index(op.f('ix_statistics_task_task_type'), 'statistics_task', ['task_type'], unique=False)
    
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_id'), 'relationships', ['id'], unique=False)
    op.create_index(op.f('ix_relationships_source_id'), 'relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_relationships_relation_type'), 'relationships', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_relation_type'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_id'), table_name='relationships')
    op.drop_table('relationships')
    
    op.drop_index(op.f('ix_statistics_task_task_type'), table_name='statistics_task')
    op.drop_index(op.f('ix_statistics_task_status'), table_name='statistics_task')
    op.drop_index(op.f('ix_statistics_task_id'), table_name='statistics_task')
    op.drop_index(op.f('ix_statistics_task_created_at'), table_name='statistics_task')
    op.drop_table('statistics_task')
    
    op.drop_index(op.f('ix_statistics_cache_id'), table_name='statistics_cache')
    op.drop_index(op.f('ix_statistics_cache_expires_at'), table_name='statistics_cache')
    op.drop_index(op.f('ix_statistics_cache_cache_key'), table_name='statistics_cache')
    op.drop_table('statistics_cache')
    
    op.drop_index(op.f('ix_import_records_id'), table_name='import_records')
    op.drop_table('import_records')
    
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
